In [2]:
import pandas as pd


In [3]:
obj = pd.Series([4, 7, -5, 3])
obj


0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.array


<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [5]:
obj.index


RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2


d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index


Index(['d', 'b', 'a', 'c'], dtype='object')

In [8]:
obj2['a']


-5

In [9]:
obj2['d']


4

In [10]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]


c    3
a   -5
d    6
dtype: int64

In [11]:
obj2[obj2 > 0]


d    6
b    7
c    3
dtype: int64

In [12]:
obj2*2


d    12
b    14
a   -10
c     6
dtype: int64

In [13]:
import numpy as np
np.exp(obj2)


d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [14]:
'b' in obj2


True

In [15]:
'e' in obj2


False

In [16]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}


In [17]:
obj3 = pd.Series(sdata)


In [18]:
obj3


Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
obj3.to_dict()


{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [20]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
pd.isna(obj4)


California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
pd.notna(obj4)


California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [23]:
obj3


Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
obj3+obj4


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [26]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4


state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [27]:
obj


0    4
1    7
2   -5
3    3
dtype: int64

In [28]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj


Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [29]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)


In [30]:
frame


state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [31]:
frame.head()


state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [32]:
frame.tail()


state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [33]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'])


In [34]:
frame2


year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [35]:
frame2.columns


Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [36]:
frame2['state']


0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [37]:
frame.year


0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [38]:
frame2.loc[1]


year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [39]:
frame2['debt'] = 16.5


In [40]:
frame2


year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [41]:
frame2['debt'] = np.arange(6.)
frame2


year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [42]:
val = pd.Series([-12., -1.5, -1.7], index=['two', 'four', 'five'])

frame2['debt'] = val
frame2


year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [43]:
test = {'a': 1, 'b': 2}
test


{'a': 1, 'b': 2}

In [44]:
del test['a']
test


{'b': 2}

In [45]:
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2


year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [46]:
del frame2['eastern']
frame2.columns


Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [47]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}


In [48]:
import pandas as pd
frame3 = pd.DataFrame(populations)
frame3


Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [49]:
frame3.T


2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [50]:
import numpy as np

pd.DataFrame(populations, index=[2001, 2002, 2003])


Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [51]:
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)


Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [52]:
frame3['Ohio'][:-1]


2000    1.5
2001    1.7
Name: Ohio, dtype: float64

In [53]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3


state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [54]:

frame3.to_numpy()


array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [55]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
data


{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [56]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2


year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [57]:
frame2.values


array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [58]:
frame2.to_numpy()


array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [59]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj


a    0
b    1
c    2
dtype: int64

In [60]:
index = obj.index


In [61]:
index


Index(['a', 'b', 'c'], dtype='object')

In [62]:
index[1:]


Index(['b', 'c'], dtype='object')

In [63]:
labels = pd.Index(np.arange(3))


In [64]:
labels


Int64Index([0, 1, 2], dtype='int64')

In [65]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)


In [66]:
obj2


0    1.5
1   -2.5
2    0.0
dtype: float64

In [67]:
obj2.index is labels


True

In [68]:
frame3


state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [69]:
frame3.columns


Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [70]:
'Ohio' in frame3.columns


True

In [71]:
2003 in frame3.index


False

In [72]:
pd.Index(['foo', 'foo', 'bar', 'bar'])


Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [73]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", 'b', 'a', 'c'])
obj


d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [74]:
obj2 = obj.reindex(['a', 'b', 'c', 'e', 'd'])


In [75]:
obj2


a   -5.3
b    7.2
c    3.6
e    NaN
d    4.5
dtype: float64

In [76]:
obj3 = pd.Series(['blue', 'purplr', 'yellow'], index=[0, 2, 4])
obj3


0      blue
2    purplr
4    yellow
dtype: object

In [77]:
obj3.reindex(np.arange(6), method='ffill')


0      blue
1      blue
2    purplr
3    purplr
4    yellow
5    yellow
dtype: object

In [78]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame


Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [79]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'])
frame2


Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [80]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)


Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [81]:
frame.reindex(states, axis='columns')


Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [82]:
frame.reindex(states)


Ohio  Texas  California
Texas        NaN    NaN         NaN
Utah         NaN    NaN         NaN
California   NaN    NaN         NaN

In [83]:
frame


Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [84]:
frame.loc[['a', 'd', 'c'], ['California', 'Texas']]


California  Texas
a           2      1
d           8      7
c           5      4

In [85]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj


a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [86]:
new_obj = obj.drop('c')
new_obj


a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [87]:
obj.drop(['d', 'c'])


a    0.0
b    1.0
e    4.0
dtype: float64

In [88]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [89]:
data.drop(index=['Colorado', 'Ohio'])


one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [90]:
data.drop(columns=['two'])


one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [91]:
data.drop('two', axis=1)


one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [92]:
data.drop(['two', 'four'], axis='columns')


one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [93]:
obj


a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [94]:
test = obj.drop('c')


In [95]:
test


a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [96]:
test['a'] = 2
test


a    2.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [97]:

obj


a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [98]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj


a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [99]:
obj[1]


1.0

In [100]:
obj[2:4]


c    2.0
d    3.0
dtype: float64

In [101]:
obj[obj < 2]


a    0.0
b    1.0
dtype: float64

In [102]:
obj['b':'c']


b    1.0
c    2.0
dtype: float64

In [103]:
obj[1:2]


b    1.0
dtype: float64

In [104]:
obj['b':'c'] = 5


In [105]:
obj


a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [106]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj1
obj2
obj1[[0, 1, 2]]


0    2
1    3
2    1
dtype: int64

In [107]:
obj2[[0, 1, 2]]


a    1
b    2
c    3
dtype: int64

In [108]:
obj.loc['b']


5.0

In [109]:
obj.iloc[0]


0.0

In [110]:
obj.iloc[[0, 1, 2]]


a    0.0
b    5.0
c    5.0
dtype: float64

In [111]:
obj2.loc['b':'c']


b    2
c    3
dtype: int64

In [112]:
obj2.loc['b', 'c'] = 5
obj2


a    1
b    5
c    5
dtype: int64

In [113]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data['two']


Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [115]:
data[['three', 'one']]


three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [116]:
data[:2]


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [117]:
data[data['three'] > 5]


one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
data['three'] > 5


Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [119]:
data < 5


one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [120]:
data[data < 5] = 0


In [121]:
data


one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
data.loc['Colorado', ['two', 'three']]


two      5
three    6
Name: Colorado, dtype: int32

In [123]:
data.iloc[2, [3, 0, 1]]


four    11
one      8
two      9
Name: Utah, dtype: int32

In [124]:
data.iloc[0]


one      0
two      0
three    0
four     0
Name: Ohio, dtype: int32

In [125]:
data.loc[['Colorado', 'New York']]


one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [126]:
data.iloc[0:1]


one  two  three  four
Ohio    0    0      0     0

In [127]:
data.iloc[[2, 1]]


one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [128]:
data[0:2]


one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7

In [129]:
data.iloc[:, :3]


one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [130]:
data.iloc[:, :3][data.three > 5]


one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [131]:
data.iloc[1:2]


one  two  three  four
Colorado    0    5      6     7

In [132]:
ser = pd.Series(np.arange(3.))


In [133]:
ser


0    0.0
1    1.0
2    2.0
dtype: float64

In [134]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]


2.0

In [135]:
ser[:1]


0    0.0
dtype: float64

In [136]:
ser.loc[:1]


0    0.0
1    1.0
dtype: float64

In [137]:
ser.iloc[:1]


0    0.0
dtype: float64

In [138]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])


In [139]:
s1


a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [140]:
s2


a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [141]:
s1+s2


a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [142]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list(
    'bcd'), index=['Ohio', 'Texas', 'Colorado'])
df1


b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [143]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list(
    'bde'), index=['Utah', 'Ohio', 'texas', 'oregon'])
df2


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
texas   6.0   7.0   8.0
oregon  9.0  10.0  11.0

In [144]:
df1+df2


b   c    d   e
Colorado  NaN NaN  NaN NaN
Ohio      3.0 NaN  6.0 NaN
Texas     NaN NaN  NaN NaN
Utah      NaN NaN  NaN NaN
oregon    NaN NaN  NaN NaN
texas     NaN NaN  NaN NaN

In [145]:
df1 = pd.DataFrame({'A': [1, 2]})
df1


A
0  1
1  2

In [146]:
df2 = pd.DataFrame({'B': [3, 4]})


In [147]:
df2


B
0  3
1  4

In [148]:
df1+df2


A   B
0 NaN NaN
1 NaN NaN

In [149]:
df1-df2


A   B
0 NaN NaN
1 NaN NaN

In [150]:
df1 = pd.DataFrame(np.arange(12.).reshape(3, 4), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape(4, 5), columns=list('abcde'))
df1


a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [151]:
df2


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [152]:
df2


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [153]:
df2[:]
df2[0:1]
df2['a']


0     0.0
1     5.0
2    10.0
3    15.0
Name: a, dtype: float64

In [154]:
df2.loc[1]['b'] = 0


In [155]:
df2


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   0.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [156]:
df3 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'), index=list('efg'))
df3


a    b     c     d
e  0.0  1.0   2.0   3.0
f  4.0  5.0   6.0   7.0
g  8.0  9.0  10.0  11.0

In [157]:
df3.loc['e']['a'] = 12


In [158]:
df3


a    b     c     d
e  12.0  1.0   2.0   3.0
f   4.0  5.0   6.0   7.0
g   8.0  9.0  10.0  11.0

In [209]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [173]:
data[data < 5] = 0


In [210]:
data.loc[:, "one"] = 1
data


one  two  three  four
Ohio        1    1      2     3
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [197]:
data.iloc[2] = 5
data


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        5    5      5     5
New York   12   13     14    15

In [200]:
data.loc[data["four"] > 5] = 3
data


one  two  three  four
Ohio        0    1      2     3
Colorado    3    3      3     3
Utah        3    3      3     3
New York    3    3      3     3

In [211]:
data.loc['Utah']['three'] = 6
data


C:\Users\gyh\AppData\Local\Temp\ipykernel_17028\1995771642.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc['Utah']['three']=6


one  two  three  four
Ohio        1    1      2     3
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [205]:

data
data.loc[data['three'] == 2]["three"] = 6
data


C:\Users\gyh\AppData\Local\Temp\ipykernel_17028\2603303598.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data['three'] == 2]["three"] = 6


one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [212]:
df1


a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [213]:
df2


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   0.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df2.loc[1, 'b'] = np.nan


In [214]:
df2


a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   0.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [215]:
df1+df2


a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   5.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [216]:
df1.add(df2, fill_value=0)


a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [217]:
1/df1


a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [218]:
df1.rdiv(1)


a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [219]:
df1.div(1)


a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [220]:
df1.reindex(columns=df2.columns, fill_value=0)


a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [221]:
arr = np.arange(12.).reshape((3, 4))


In [222]:
arr


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [223]:
arr[0]


array([0., 1., 2., 3.])

In [224]:
arr-arr[0]


array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [225]:
arr[:][0]


array([0., 1., 2., 3.])

In [226]:
arr[:, 0]


array([0., 4., 8.])

In [227]:
frame = pd.DataFrame(np.arange(12.).reshape(4, 3), 
                     columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

series = frame.iloc[0]

frame


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [228]:

series


b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [230]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [231]:
series2=pd.Series(range(3),index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [232]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [233]:
series3=frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [234]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [235]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [236]:
frame.sub(series3,axis='index')


b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [237]:
frame.sub(series3,axis='columns')

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [238]:
frame=pd.DataFrame(np.random.standard_normal((4,3)),
                   columns=list('bde'),
                   index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah   -0.855450  0.085834  1.121508
Ohio    0.672462  1.203719 -1.383137
Texas  -0.390984  0.234905  0.369738
Oregon -0.454511 -1.509197  1.390764

In [239]:
np.abs(frame)

b         d         e
Utah    0.855450  0.085834  1.121508
Ohio    0.672462  1.203719  1.383137
Texas   0.390984  0.234905  0.369738
Oregon  0.454511  1.509197  1.390764

In [242]:
f=lambda x:x.max()-x.min()

frame.apply(f)

b    1.527912
d    2.712916
e    2.773902
dtype: float64

In [243]:
frame.apply(f,axis='columns')

Utah      1.976958
Ohio      2.586856
Texas     0.760722
Oregon    2.899962
dtype: float64

In [244]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

frame.apply(f)
                     

b         d         e
min -0.855450 -1.509197 -1.383137
max  0.672462  1.203719  1.390764

In [245]:

format=lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.86   0.09   1.12
Ohio     0.67   1.20  -1.38
Texas   -0.39   0.23   0.37
Oregon  -0.45  -1.51   1.39

In [246]:
frame['e'].map(format)

Utah       1.12
Ohio      -1.38
Texas      0.37
Oregon     1.39
Name: e, dtype: object

In [247]:
obj=pd.Series(range(4),index=['d','a','b','c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [248]:

obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [249]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),
                   index=['three','one'],
                   columns=['d','a','b','c'])
frame
                

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [250]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [251]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [252]:

frame.sort_index(axis='columns',ascending=False)


d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [253]:
obj=pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [255]:

obj=pd.Series([4,np.nan,7,np.nan,-3,2])
obj.sort_values()
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [256]:
frame=pd.DataFrame({'b':[4,7,-3,2], "a": [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [257]:

frame.sort_values('b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [258]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [259]:
frame.sort_values(['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [260]:

obj=pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [262]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [263]:
obj.rank(ascending=False,method='max')


0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [265]:
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [266]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [267]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [269]:
frame.rank(axis='index')

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [270]:
obj=pd.Series(np.arange(5),index=['a', 'a','b', 'b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [272]:
obj.index.is_unique

False

In [273]:
obj['a']

a    0
a    1
dtype: int32

In [274]:
obj['c']

4

In [277]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan],[0.75,-1.3]])
df

0    1
0  1.40  NaN
1  7.10 -4.5
2   NaN  NaN
3  0.75 -1.3

In [278]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan],[0.75,-1.3]],
                index=['a','b','c','d'],
                columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [279]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [280]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [281]:
df.loc['b']

one    7.1
two   -4.5
Name: b, dtype: float64

In [282]:
df.sum(axis='index',skipna=False)

one   NaN
two   NaN
dtype: float64

In [284]:
df.sum(axis='columns',skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [285]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [287]:
df.idxmax()

one    b
two    d
dtype: object

In [288]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [289]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [290]:
obj=pd.Series(['a','a','b','c']*4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [291]:
price=pd.read_pickle('examples/yahoo_price.pkl')
volume=pd.read_pickle('examples/yahoo_volume.pkl')


In [292]:
returns= price.pct_change()
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [294]:
returns['MSFT'].corr(returns['IBM'])


0.4997636114415116

In [295]:
returns['MSFT'].cov(returns['IBM'])


8.870655479703548e-05

In [296]:
returns.MSFT.corr(returns.IBM)

0.4997636114415116

In [297]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [298]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [299]:
returns.corrwith(returns.IBM)

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [300]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [301]:
volume

AAPL      GOOG       IBM      MSFT
Date                                               
2010-01-04  123432400   3927000   6155300  38409100
2010-01-05  150476200   6031900   6841400  49749600
2010-01-06  138040000   7987100   5605300  58182400
2010-01-07  119282800  12876600   5840600  50559700
2010-01-08  111902700   9483900   4197200  51197400
...               ...       ...       ...       ...
2016-10-17   23624900   1089500   5890400  23830000
2016-10-18   24553500   1995600  12770600  19149500
2016-10-19   20034600    116600   4632900  22878400
2016-10-20   24125800   1734200   4023100  49455600
2016-10-21   22384800   1260500   4401900  79974200

[1714 rows x 4 columns]

In [302]:
obj=pd.Series(['c','a','d','a','a','b','b','c','c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [304]:
uniques=obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [305]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [306]:
pd.value_counts(obj.values,sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [307]:
pd.value_counts(obj.to_numpy(),sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [308]:
mask=obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [310]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [311]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [313]:
to_match=pd.Series(['c','a','b','b','c','a'])
unique_vals=pd.Series(['c','b','a'])
indices=pd.Index(unique_vals).get_indexer(to_match)
indices

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [315]:
data=pd.DataFrame({'Qu1':[1,3,4,3,4],
                   'Qu2':[2,3,1,2,3],
                   'Qu3':[1,5,2,4,4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [316]:
result=data.apply(pd.value_counts).fillna(0)

In [317]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0