In [91]:
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 25
pd.options.display.max_columns = 20
pd.options.display.max_colwidth = 82
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [92]:
float_data =pd.Series([1.2,-3.5,np.nan,0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [93]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [94]:
string_data=pd.Series(['aardvark',np.nan,None,'avocado'])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [95]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [96]:
float_data=pd.Series([1,2,None],dtype='float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [97]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [98]:
data=pd.Series([1,np.nan,3.5,np.nan,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [99]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [100]:
data=pd.DataFrame([[1.,6.5,3.],[1.,np.nan,np.nan],
                   [np.nan,np.nan,np.nan],[np.nan,6.5,3.]])
data
                  

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [101]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [102]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [103]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [104]:
data[4]=np.nan

In [105]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [106]:
data.dropna(axis='columns',how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [107]:
df=pd.DataFrame(np.random.standard_normal((7,3)))
df.iloc[:4,1]=np.nan
df.iloc[:2,2]=np.nan
df

0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [108]:
df.dropna()

0         1         2
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [109]:
df.dropna(thresh=2)

0         1         2
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [110]:
df.fillna(0)

0         1         2
0 -0.204708  0.000000  0.000000
1 -0.555730  0.000000  0.000000
2  0.092908  0.000000  0.769023
3  1.246435  0.000000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [111]:
df.fillna({1:0.5,2:0})

0         1         2
0 -0.204708  0.500000  0.000000
1 -0.555730  0.500000  0.000000
2  0.092908  0.500000  0.769023
3  1.246435  0.500000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [112]:
df.fillna(0,inplace=True)


In [113]:
df

0         1         2
0 -0.204708  0.000000  0.000000
1 -0.555730  0.000000  0.000000
2  0.092908  0.000000  0.769023
3  1.246435  0.000000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [114]:
df=pd.DataFrame(np.random.standard_normal((6,3)))
df.iloc[2:,1]=np.nan
df.iloc[4:,2]=np.nan
df

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772       NaN  1.343810
3 -0.713544       NaN -2.370232
4 -1.860761       NaN       NaN
5 -1.265934       NaN       NaN

In [115]:
df.fillna(method='ffill')

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772  0.124121  1.343810
3 -0.713544  0.124121 -2.370232
4 -1.860761  0.124121 -2.370232
5 -1.265934  0.124121 -2.370232

In [116]:
df.fillna(method='ffill',limit=2)

0         1         2
0  0.476985  3.248944 -1.021228
1 -0.577087  0.124121  0.302614
2  0.523772  0.124121  1.343810
3 -0.713544  0.124121 -2.370232
4 -1.860761       NaN -2.370232
5 -1.265934       NaN -2.370232

In [117]:
data=pd.Series([1,np.nan,3.5,np.nan,7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [118]:
data=pd.DataFrame({'k1':['one','two']*3+['two'],
                   'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [119]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [120]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [121]:
data['v1']=range(7)


In [122]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [123]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [124]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [125]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [126]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}


In [127]:
data['animal']=data['food'].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [128]:
def get_animal(x):
    return meat_to_animal[x]
data['food'].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [129]:
data=pd.Series([1.,-999.,2.,-999.,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [130]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [131]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [132]:
data.replace([-999,-1000],np.nan)


0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [133]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [134]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [135]:
data=pd.DataFrame(np.arange(12).reshape((3, 4)),
                  index=['Ohio','Colorado','New York'],
                  columns=['one','two','three','four'])

In [136]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [137]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [138]:
data.index=data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [139]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [140]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [141]:
data.rename(index={'Ohio':'INDIANA'},
            columns={'three':'peekaboo'})


one  two  peekaboo  four
OHIO    0    1         2     3
COLO    4    5         6     7
NEW     8    9        10    11

In [142]:
data.rename(index={'OHIO':'INDIANA'},inplace=True)

In [143]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [144]:
ages=[20,22,25,27,21,23,37,31, 61, 45, 41, 32]
bins=[18,25,35,60,100]
age_categories=pd.cut(ages,bins)

In [145]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [146]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [147]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [148]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [149]:
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [150]:
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [151]:
group_names=['YOuth','YoungAdult','MiddleAged','Senior']
pd.cut(ages,bins,labels=group_names)

['YOuth', 'YOuth', 'YOuth', 'YoungAdult', 'YOuth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['YOuth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [152]:
data=np.random.uniform(size=20)
pd.cut(data,4,precision=2)

[(0.34, 0.55], (0.34, 0.55], (0.76, 0.97], (0.76, 0.97], (0.34, 0.55], ..., (0.34, 0.55], (0.34, 0.55], (0.55, 0.76], (0.34, 0.55], (0.12, 0.34]]
Length: 20
Categories (4, interval[float64, right]): [(0.12, 0.34] < (0.34, 0.55] < (0.55, 0.76] < (0.76, 0.97]]

In [153]:
data

array([0.4896, 0.3773, 0.8486, 0.9111, 0.3838, 0.3155, 0.5684, 0.1878,
       0.1258, 0.6876, 0.7996, 0.5735, 0.9732, 0.6341, 0.8884, 0.4954,
       0.3516, 0.7142, 0.5039, 0.2256])

In [154]:
data=np.random.standard_normal(1000)
quartiles=pd.qcut(data,4,precision=2)
quartiles

[(-0.026, 0.62], (0.62, 3.93], (-0.68, -0.026], (0.62, 3.93], (-0.026, 0.62], ..., (-0.68, -0.026], (-0.68, -0.026], (-2.96, -0.68], (0.62, 3.93], (-0.68, -0.026]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.96, -0.68] < (-0.68, -0.026] < (-0.026, 0.62] < (0.62, 3.93]]

In [155]:
pd.value_counts(quartiles)

(-2.96, -0.68]     250
(-0.68, -0.026]    250
(-0.026, 0.62]     250
(0.62, 3.93]       250
dtype: int64

In [156]:
pd.qcut(data,[0,0.1,0.5,0.9,1.]).value_counts()

(-2.9499999999999997, -1.187]    100
(-1.187, -0.0265]                400
(-0.0265, 1.286]                 400
(1.286, 3.928]                   100
dtype: int64

In [4]:
import pandas as pd
import numpy as np
data=pd.DataFrame(np.random.standard_normal((1000,4)))
data.describe 

<bound method NDFrame.describe of             0         1         2         3
0   -0.240314  0.122324  0.928889 -1.201498
1   -0.259401 -0.860769  0.837279 -0.434756
2    0.229993 -0.856066  0.581896  2.028316
3    0.079141 -1.846757  1.205856  0.536989
4   -1.134474 -0.519184 -0.320384  0.564946
..        ...       ...       ...       ...
995  0.397076  0.431224 -0.889559  0.094169
996 -1.183218  0.762626  0.647772  2.874023
997 -0.359136  1.293742 -0.466142  1.337051
998  1.553375 -0.097665 -1.288454 -0.896105
999  0.895020 -1.393057 -1.079087  0.631486

[1000 rows x 4 columns]>

In [5]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.036428    -0.008571    -0.012766     0.004774
std       0.998237     1.022480     0.993291     0.992309
min      -3.206483    -3.409678    -3.294768    -3.206336
25%      -0.591549    -0.733713    -0.723122    -0.671582
50%       0.013976    -0.021196    -0.010293     0.007170
75%       0.741206     0.687594     0.682532     0.697346
max       3.630071     3.630288     3.136229     2.874023

In [6]:
col=data[2]
col

0      0.928889
1      0.837279
2      0.581896
3      1.205856
4     -0.320384
         ...   
995   -0.889559
996    0.647772
997   -0.466142
998   -1.288454
999   -1.079087
Name: 2, Length: 1000, dtype: float64

In [160]:
col[col.abs()>3]

41    -3.399312
136   -3.745356
Name: 2, dtype: float64

In [163]:
data[(np.abs(data)>3).any(axis='columns')]

0         1         2         3
41   0.457246 -0.025907 -3.399312 -0.974657
60   1.951312  3.260383  0.963301  1.201206
136  0.508391 -0.196713 -3.745356 -1.520113
235 -0.242459 -3.056990  1.918403 -0.578828
258  0.682841  0.326045  0.425384 -3.428254
322  1.179227 -3.184377  1.369891 -1.074833
544 -3.548824  1.553205 -2.186301  1.277104
635 -0.578093  0.193299  1.397822  3.366626
782 -0.207434  3.525865  0.283070  0.544635
803 -3.645860  0.255475 -0.549574 -1.907459

In [164]:
arr=np.random.standard_normal((4,4))
arr

array([[-0.4579,  0.2404, -1.8396,  0.5788],
       [-1.3651,  0.1172, -0.1382, -1.2512],
       [-1.0888, -2.0936, -0.1115, -0.4756],
       [ 0.5954,  1.0176,  0.3453,  1.5885]])

In [174]:
arr>0

array([[False,  True, False,  True],
       [False,  True, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [178]:
(arr>0).any(axis=0)

array([ True,  True,  True,  True])

In [179]:
arr[(arr>0).any(axis=0)]

array([[-0.4579,  0.2404, -1.8396,  0.5788],
       [-1.3651,  0.1172, -0.1382, -1.2512],
       [-1.0888, -2.0936, -0.1115, -0.4756],
       [ 0.5954,  1.0176,  0.3453,  1.5885]])

In [176]:
(arr>0).any(axis=1)

array([ True,  True, False,  True])

In [180]:
arr[(arr>0).any(axis=1)]

array([[-0.4579,  0.2404, -1.8396,  0.5788],
       [-1.3651,  0.1172, -0.1382, -1.2512],
       [ 0.5954,  1.0176,  0.3453,  1.5885]])

In [181]:
data[(data.abs()>3).any(axis='columns')]


0         1         2         3
41   0.457246 -0.025907 -3.399312 -0.974657
60   1.951312  3.260383  0.963301  1.201206
136  0.508391 -0.196713 -3.745356 -1.520113
235 -0.242459 -3.056990  1.918403 -0.578828
258  0.682841  0.326045  0.425384 -3.428254
322  1.179227 -3.184377  1.369891 -1.074833
544 -3.548824  1.553205 -2.186301  1.277104
635 -0.578093  0.193299  1.397822  3.366626
782 -0.207434  3.525865  0.283070  0.544635
803 -3.645860  0.255475 -0.549574 -1.907459

In [182]:
data[data.abs()>3]=np.sign(data)*3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.050286     0.025567    -0.001399    -0.051765
std       0.992920     1.004214     0.991414     0.995761
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.599807    -0.612162    -0.687373    -0.747478
50%       0.047101    -0.013609    -0.022158    -0.088274
75%       0.756646     0.695298     0.699046     0.623331
max       2.653656     3.000000     2.735527     3.000000

In [183]:
data

0         1         2         3
0   -0.799318  0.777233 -0.612905  0.316447
1    0.838295 -1.034423  0.434304 -2.213133
2    0.758040  0.553933  0.339231 -0.688756
3   -0.815526 -0.332420  2.406483 -1.361428
4   -0.669619  0.781199 -0.395813 -0.180737
..        ...       ...       ...       ...
995 -0.856979 -0.446678  1.229042 -1.558031
996 -0.289339 -0.232531  0.409304 -0.813190
997  0.023646  0.232781 -0.345727  1.519174
998  1.060646 -1.456358  1.128420  0.032166
999 -0.485783  1.181563 -2.314042 -0.865834

[1000 rows x 4 columns]

In [184]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0  1.0
1  1.0 -1.0  1.0 -1.0
2  1.0  1.0  1.0 -1.0
3 -1.0 -1.0  1.0 -1.0
4 -1.0  1.0 -1.0 -1.0

In [186]:
df=pd.DataFrame(np.arange(5*7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [190]:
sampler=np.random.permutation(5)
sampler

array([3, 2, 1, 4, 0])

In [191]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [192]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [193]:
column_sampler=np.random.permutation(7)
column_sampler

array([5, 3, 2, 4, 6, 1, 0])

In [194]:
df.take(column_sampler,axis='columns')

5   3   2   4   6   1   0
0   5   3   2   4   6   1   0
1  12  10   9  11  13   8   7
2  19  17  16  18  20  15  14
3  26  24  23  25  27  22  21
4  33  31  30  32  34  29  28

In [207]:
df.sample(3)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27

In [208]:
choices=pd.Series([5,7,-1,6,4])
drwas=choices.sample(n=10,replace=True)
drwas

4    4
0    5
3    6
2   -1
2   -1
1    7
0    5
0    5
2   -1
0    5
dtype: int64

In [212]:
choices.sample(n=6,replace=True)

1    7
3    6
4    4
3    6
4    4
4    4
dtype: int64

In [213]:
type(drwas)

pandas.core.series.Series

In [217]:
drwas.describe

<bound method NDFrame.describe of 4    4
0    5
3    6
2   -1
2   -1
1    7
0    5
0    5
2   -1
0    5
dtype: int64>

In [218]:
drwas[0]

0    5
0    5
0    5
0    5
dtype: int64

In [219]:
df=pd.DataFrame({'key':['b','b','a','c','a','b'],
                 'data1':range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [220]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [221]:
dummies=pd.get_dummies(df['key'],prefix='key')


In [222]:
df_with_dummy=df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [224]:
mnames=['movie_id','title','genres']

movies=pd.read_table('datasets/movielens/movies.dat',sep='::',
                     header=None,names=mnames)
movies[:10]

C:\Users\gyh\AppData\Local\Temp\ipykernel_38196\3406317401.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  movies=pd.read_table('datasets/movielens/movies.dat',sep='::',


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [226]:
all_genres=[]
for x in movies.genres:
    all_genres.extend(x.split('|'))
all_genres


Drama          1603
Comedy         1200
Action          503
Thriller        492
Romance         471
Horror          343
Adventure       283
Sci-Fi          276
Children's      251
Crime           211
War             143
Documentary     127
Musical         114
Mystery         106
Animation       105
Fantasy          68
Western          68
Film-Noir        44
dtype: int64

In [ ]:
pd.value_counts(all_genres)

In [228]:
all_genres?

Type:        list
String form: ['Animation', "Children's", 'Comedy', 'Adventure', "Children's", 'Fantasy', 'Comedy', 'Romance',  <...> tion', 'Drama', 'Thriller', 'Thriller', 'Comedy', 'Drama', 'Drama', 'Drama', 'Drama', 'Thriller']
Length:      6408
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


In [230]:
genres=pd.unique(all_genres)

In [231]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [235]:
dummies=movies['genres'].str.get_dummies('|')
dummies.iloc[:10,:6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [237]:
movies['genres']

0        Animation|Children's|Comedy
1       Adventure|Children's|Fantasy
2                     Comedy|Romance
3                       Comedy|Drama
4                             Comedy
                    ...             
3878                          Comedy
3879                           Drama
3880                           Drama
3881                           Drama
3882                  Drama|Thriller
Name: genres, Length: 3883, dtype: object

In [239]:
movies['genres'].str?

Init signature: str(self, /, *args, **kwargs)
Docstring:     
str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to sys.getdefaultencoding().
errors defaults to 'strict'.
Type:           type
Subclasses:     DeferredConfigString, _rstr, LSString, include, ColorDepth, Keys, InputMode, CompleteStyle, SortKey, FoldedCase, ...


In [240]:
movies['genres'].str.split('|')

0        [Animation, Children's, Comedy]
1       [Adventure, Children's, Fantasy]
2                      [Comedy, Romance]
3                        [Comedy, Drama]
4                               [Comedy]
                      ...               
3878                            [Comedy]
3879                             [Drama]
3880                             [Drama]
3881                             [Drama]
3882                   [Drama, Thriller]
Name: genres, Length: 3883, dtype: object

In [244]:
movies['genres'].str[:]

0        Animation|Children's|Comedy
1       Adventure|Children's|Fantasy
2                     Comedy|Romance
3                       Comedy|Drama
4                             Comedy
                    ...             
3878                          Comedy
3879                           Drama
3880                           Drama
3881                           Drama
3882                  Drama|Thriller
Name: genres, Length: 3883, dtype: object

In [245]:
movies_windic=movies.join(dummies.add_prefix('Genre_'))

In [246]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [247]:
np.random.seed(12345)
values=np.random.uniform(size=10)
values

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536])

In [248]:
bins=[0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [249]:
s=pd.Series([1,2,3,None])
s
s.dtype

dtype('float64')

In [250]:
from pandas import Int64Dtype


s=pd.Series([1,2,3,None],dtype=Int64Dtype())
s.isna()
s.dtype

Int64Dtype()

In [251]:
s[3]

<NA>

In [252]:
s[3] is pd.NA

True

In [253]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [254]:
s=pd.Series([1,2,3,None],dtype='Int64')
s=pd.Series(['one','two',None,'three'],dtype=pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [259]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})

df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [260]:
df.dtypes

A    float64
B     object
C     object
dtype: object

In [256]:
df["A"] = df["A"].astype("Int64")

In [257]:
df["B"] = df["B"].astype("string")
df["C"] = df["C"].astype("boolean")

In [258]:
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [261]:
val='a,b,   guido'
val.split(',')

['a', 'b', '   guido']

In [262]:
pieces=[x.strip() for x in val.split(',')]

In [263]:
pieces

['a', 'b', 'guido']

In [264]:
first,second,third=pieces
first+'::'+second+'::'+third

'a::b::guido'

In [265]:
'::'.join(pieces)

'a::b::guido'

In [266]:
'guido' in val

True

In [267]:
val.index(',')

1

In [268]:
val.find(':')

-1

In [269]:
val.index(':')

ValueError: substring not found

In [270]:
val.count(',')

2

In [271]:
val.replace(',','::')


'a::b::   guido'

In [272]:
val.replace(',','')

'ab   guido'

In [273]:
import re 
text='foo   bar\t baz   \tqux'

In [275]:
re.split(r'\s+',text)

['foo', 'bar', 'baz', 'qux']

In [276]:
regex=re.compile("\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [277]:
regex.findall(text)

['   ', '\t ', '   \t']

In [279]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex=re.compile(pattern,flags=re.IGNORECASE)


In [280]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [281]:
m=regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [282]:
text[m.start():m.end()]

'dave@google.com'

In [284]:
print(regex.match(text))

None


In [285]:
print(regex.sub('REDACTED',text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [293]:
pattern=r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex=re.compile(pattern,flags=re.IGNORECASE)

In [294]:
m=regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [295]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [297]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3',text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [299]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}
data=pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [300]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [301]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [303]:
data_as_string_ext=data.astype('string')
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [304]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [305]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [306]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [307]:
matches=data.str.findall(pattern,flags=re.IGNORECASE).str[0]

In [308]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [309]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [310]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [311]:
se=pd.Series([1,2,3,4])
se

0    1
1    2
2    3
3    4
dtype: int64

In [312]:
se[0:1]

0    1
dtype: int64

In [314]:
data.str.extract(pattern,flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [318]:
values=pd.Series(['apple','orange','apple','apple']*2)
values


0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [319]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [320]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [321]:
values=pd.Series([0,1,0,0]*2)
dim=pd.Series(['apple','orange'])
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [322]:
dim

0     apple
1    orange
dtype: object

In [323]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [324]:
fruits=['apple','orange','apple','apple']*2
N=len(fruits)

In [325]:
N

8

In [326]:
print(N)

8


In [327]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [331]:
rng=np.random.default_rng(seed=12345)
df=pd.DataFrame({'fruit':fruits,
                 'basket_id':np.arange(N),
                 'count':rng.integers(3,15,size=N),
                 'weight':rng.uniform(0,4,size=N)},
                columns=['basket_id','fruit','count','weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [332]:
fruit_cat=df['fruit'].astype('category')

In [333]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [334]:
c=fruit_cat.array

In [335]:
type(c)

pandas.core.arrays.categorical.Categorical

In [336]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [337]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [338]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [340]:
enumerate(c.categories)

In [341]:
df['fruit']=df['fruit'].astype('category')

In [342]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [343]:
my_categories=pd.Categorical(['foo','bar','baz','foo','bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [344]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cat_2=pd.Categorical.from_codes(codes,categories)

In [345]:
my_cat_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [346]:
ordered_cat=pd.Categorical.from_codes(codes,categories,ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [348]:
rng=np.random.default_rng(seed=12345)
draws=rng.standard_normal(1000)
draws[:5]

array([-1.4238,  1.2637, -0.8707, -0.2592, -0.0753])

In [349]:
bins=pd.qcut(draws,4)

In [350]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [353]:
bins=pd.qcut(draws,4,labels=['Q1','Q2','Q3','Q4'])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [354]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [359]:
bins=pd.Series(bins,name='quartile')
results=(pd.Series(draws).groupby(bins).agg(['count','min','max']).reset_index())

In [357]:
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [358]:
results=(pd.Series(draws).groupby(bins).agg(['count','min','max']))
results

count       min       max
quartile                           
Q1          250 -3.119609 -0.678494
Q2          250 -0.673305  0.008009
Q3          250  0.018753  0.686183
Q4          250  0.688282  3.211418

In [360]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [361]:
N=10_000_000

labels=pd.Series(['foo','bar','baz','qux']*(N//4))
categories=labels.astype('category')


In [362]:
labels.memory_usage(deep=True)
categories.memory_usage(deep=True)



10000540

In [363]:
%time _=labels.astype('category')

CPU times: total: 359 ms
Wall time: 351 ms


In [364]:
%timeit labels.value_counts()
%timeit categories.value_counts()

289 ms ± 5.55 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
48.4 ms ± 836 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [365]:
s = pd.Series(['a','b','c','d']*2)
cat_s=s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [366]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [367]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [368]:
actual_categories=['a','b','c','d','e']
cat_s2=cat_s.cat.set_categories(actual_categories)

In [369]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [370]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [371]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In [372]:
cat_s3=cat_s[cat_s.isin(['a','b'])]

In [374]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [375]:
cat_s=pd.Series(['a','b','c','d']*2,dtype='category')
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1